title: Pixel – Satellite-Based Environmental Data Analysis
description: Sitio web oficial
theme: just-the-docs
url: "https://pixel-ong.github.io/mi-sitio"  # reemplazá con tu URL real
color_scheme: light

nav:
  - title: Inicio
    url: /
  - title: Misión
    url: /mision
  - title: Proyectos
    url: /proyectos
  - title: Integrantes
    url: /integrantes
