name: Build and Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.3'

      - name: Build site
        run: hugo --source site --destination ./

      - name: Clean Hugo source
        run: |
          rm -rf site
          rm -rf .github

      - name: Commit and push built site
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 Auto-build Fiction Hugo site"
